baseURL = "/"
languageCode = "en-gb"
title = "JS Bin help"
googleAnalytics = "UA-1656750-13"
pygmentsCodeFences = true
enableGitInfo = true
pygmentsStyle = "vs"

[outputs]
home = ["RSS", "HTML"]
page = ["HTML", "JSON"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[outputFormats.JSON]
mediatype = "application/json"
baseName = "all"

[params]
helpRoot = "https://help.jsbin.com/"
